import { Metadata } from "next";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import JsonLd from "@/components/seo/JsonLd";
import { generatePageMetadata, generateBreadcrumbJsonLd } from "@/lib/seo";

export const metadata: Metadata = generatePageMetadata({
  title: "Terms & Conditions — The QR Code Generator",
  description:
    "Read the Terms & Conditions for using The QR Code Generator. Information regarding acceptable use, dynamic QR code management, and service policies.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <>
      <JsonLd
        data={generateBreadcrumbJsonLd([
          { name: "Home", path: "/" },
          { name: "Terms & Conditions", path: "/terms" },
        ])}
      />

      <Navbar />

      <main className="bg-canvas py-16 md:py-24">
        <div className="container-main max-w-3xl">
          <div className="text-center mb-12">
            <h1 className="display-heading text-4xl font-semibold text-ink leading-tight">
              Terms &amp; Conditions
            </h1>
            <p className="mt-2 text-sm text-body-mid">
              Last updated: July 2026
            </p>
          </div>

          <div className="prose prose-slate max-w-none space-y-6 text-body leading-relaxed border-t border-hairline pt-8">
            <p>
              Welcome to <strong>The QR Code Generator</strong>. By accessing or using our website (TheQRCod.com) and associated QR generation services, you agree to comply with and be bound by the following Terms &amp; Conditions.
            </p>

            <h2 className="text-xl font-semibold text-ink pt-4">1. Use of Service</h2>
            <p>
              You agree to use our platform only for lawful purposes. You must not generate QR codes that redirect to illegal content, malware, phishing sites, or materials that violate intellectual property rights.
            </p>

            <h2 className="text-xl font-semibold text-ink pt-4">2. Static vs Dynamic QR Codes</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Static QR Codes:</strong> Provided free of charge with no expiration. We guarantee perpetual operation of static codes as they encode data directly.</li>
              <li><strong>Dynamic QR Codes:</strong> Rely on redirect servers. Active dynamic codes require a valid account or active subscription status.</li>
            </ul>

            <h2 className="text-xl font-semibold text-ink pt-4">3. Intellectual Property</h2>
            <p>
              All QR codes generated by you using our platform, including uploaded logos and customized visual designs, remain your property. The platform interface and code infrastructure remain the exclusive property of The QR Code Generator.
            </p>

            <h2 className="text-xl font-semibold text-ink pt-4">4. Limitation of Liability</h2>
            <p>
              While we strive for 99.9% service uptime, The QR Code Generator will not be liable for damages resulting from user input errors, destination server downtime, or unreadable print quality.
            </p>

            <h2 className="text-xl font-semibold text-ink pt-4">5. Contact Information</h2>
            <p>
              For questions regarding these Terms &amp; Conditions, please email <strong>legal@theqrcod.com</strong>.
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
}
